spring.datasource.url: jdbc:h2:file:./camunda-h2-database
loggingfile: logs/app.log
spring.h2.console:
      enabled: true
      path: /h2

camunda.bpm.admin-user:
  id: demo
  password: demo


server:
  port: 9090
